#!/usr/bin/env python3
"""Generate EMSRouting.xcodeproj/project.pbxproj"""
import os

BASE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(BASE, "EMSRouting.xcodeproj", "project.pbxproj")
os.makedirs(os.path.dirname(OUT), exist_ok=True)

P      = "AABBCC000000000000000001"
MG     = "AABBCC000000000000000002"
PG     = "AABBCC000000000000000003"
TARGET = "AABBCC000000000000000004"
SRC_PH = "AABBCC000000000000000005"
RES_PH = "AABBCC000000000000000006"
FWK_PH = "AABBCC000000000000000007"
PDBG   = "AABBCC000000000000000008"
PREL   = "AABBCC000000000000000009"
TDBG   = "AABBCC000000000000000010"
TREL   = "AABBCC000000000000000011"
PCL    = "AABBCC000000000000000012"
TCL    = "AABBCC000000000000000013"
SG     = "AABBCC000000000000000050"
PROD   = "AABBCC000000000000000060"

FILES = [
    ("EMSRoutingApp.swift",  "AABBCC000000000000000020", "AABBCC000000000000000021"),
    ("ContentView.swift",    "AABBCC000000000000000022", "AABBCC000000000000000023"),
    ("Models.swift",         "AABBCC000000000000000024", "AABBCC000000000000000025"),
    ("APIClient.swift",      "AABBCC000000000000000026", "AABBCC000000000000000027"),
    ("RoutingView.swift",    "AABBCC000000000000000028", "AABBCC000000000000000029"),
    ("DashboardView.swift",  "AABBCC000000000000000030", "AABBCC000000000000000031"),
    ("SimulationView.swift", "AABBCC000000000000000032", "AABBCC000000000000000033"),
    ("SpeechManager.swift",  "AABBCC000000000000000034", "AABBCC000000000000000035"),
    ("OfflineRouter.swift",  "AABBCC000000000000000036", "AABBCC000000000000000037"),
]
IREF = "AABBCC000000000000000040"
AREF = "AABBCC000000000000000041"
ABF  = "AABBCC000000000000000042"
JREF = "AABBCC000000000000000043"  # hospitals.json
JBF  = "AABBCC000000000000000044"  # hospitals.json in Resources

L = []
def s(line=""):
    L.append(line)

s("// !$*UTF8*$!")
s("{")
s("\tarchiveVersion = 1;")
s("\tclasses = {")
s("\t};")
s("\tobjectVersion = 56;")
s("\tobjects = {")
s()
s("/* Begin PBXBuildFile section */")
for name, ref, bf in FILES:
    s(f"\t\t{bf} /* {name} in Sources */ = {{isa = PBXBuildFile; fileRef = {ref} /* {name} */; }};")
s(f"\t\t{ABF} /* Assets.xcassets in Resources */ = {{isa = PBXBuildFile; fileRef = {AREF} /* Assets.xcassets */; }};")
s(f"\t\t{JBF} /* hospitals.json in Resources */ = {{isa = PBXBuildFile; fileRef = {JREF} /* hospitals.json */; }};")
s("/* End PBXBuildFile section */")
s()
s("/* Begin PBXFileReference section */")
s(f"\t\t{PROD} /* EMSRouting.app */ = {{isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = EMSRouting.app; sourceTree = BUILT_PRODUCTS_DIR; }};")
for name, ref, _ in FILES:
    s(f'\t\t{ref} /* {name} */ = {{isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = {name}; sourceTree = "<group>"; }};')
s(f'\t\t{IREF} /* Info.plist */ = {{isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; }};')
s(f'\t\t{AREF} /* Assets.xcassets */ = {{isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; path = Assets.xcassets; sourceTree = "<group>"; }};')
s(f'\t\t{JREF} /* hospitals.json */ = {{isa = PBXFileReference; lastKnownFileType = text.json; path = hospitals.json; sourceTree = "<group>"; }};')
s("/* End PBXFileReference section */")
s()
s("/* Begin PBXFrameworksBuildPhase section */")
s(f"\t\t{FWK_PH} /* Frameworks */ = {{")
s("\t\t\tisa = PBXFrameworksBuildPhase;")
s("\t\t\tbuildActionMask = 2147483647;")
s("\t\t\tfiles = (")
s("\t\t\t);")
s("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
s("\t\t};")
s("/* End PBXFrameworksBuildPhase section */")
s()
s("/* Begin PBXGroup section */")
s(f"\t\t{MG} = {{")
s("\t\t\tisa = PBXGroup;")
s("\t\t\tchildren = (")
s(f"\t\t\t\t{SG} /* EMSRouting */,")
s(f"\t\t\t\t{PG} /* Products */,")
s("\t\t\t);")
s('\t\t\tsourceTree = "<group>";')
s("\t\t};")
s(f"\t\t{PG} /* Products */ = {{")
s("\t\t\tisa = PBXGroup;")
s("\t\t\tchildren = (")
s(f"\t\t\t\t{PROD} /* EMSRouting.app */,")
s("\t\t\t);")
s("\t\t\tname = Products;")
s('\t\t\tsourceTree = "<group>";')
s("\t\t};")
s(f"\t\t{SG} /* EMSRouting */ = {{")
s("\t\t\tisa = PBXGroup;")
s("\t\t\tchildren = (")
for name, ref, _ in FILES:
    s(f"\t\t\t\t{ref} /* {name} */,")
s(f"\t\t\t\t{AREF} /* Assets.xcassets */,")
s(f"\t\t\t\t{JREF} /* hospitals.json */,")
s(f"\t\t\t\t{IREF} /* Info.plist */,")
s("\t\t\t);")
s("\t\t\tpath = EMSRouting;")
s('\t\t\tsourceTree = "<group>";')
s("\t\t};")
s("/* End PBXGroup section */")
s()
s("/* Begin PBXNativeTarget section */")
s(f"\t\t{TARGET} /* EMSRouting */ = {{")
s("\t\t\tisa = PBXNativeTarget;")
s(f'\t\t\tbuildConfigurationList = {TCL} /* Build configuration list for PBXNativeTarget "EMSRouting" */;')
s("\t\t\tbuildPhases = (")
s(f"\t\t\t\t{SRC_PH} /* Sources */,")
s(f"\t\t\t\t{FWK_PH} /* Frameworks */,")
s(f"\t\t\t\t{RES_PH} /* Resources */,")
s("\t\t\t);")
s("\t\t\tbuildRules = (")
s("\t\t\t);")
s("\t\t\tdependencies = (")
s("\t\t\t);")
s("\t\t\tname = EMSRouting;")
s("\t\t\tproductName = EMSRouting;")
s(f"\t\t\tproductReference = {PROD} /* EMSRouting.app */;")
s('\t\t\tproductType = "com.apple.product-type.application";')
s("\t\t};")
s("/* End PBXNativeTarget section */")
s()
s("/* Begin PBXProject section */")
s(f"\t\t{P} /* Project object */ = {{")
s("\t\t\tisa = PBXProject;")
s("\t\t\tattributes = {")
s("\t\t\t\tBuildIndependentTargetsInParallel = 1;")
s("\t\t\t\tLastSwiftUpdateCheck = 1500;")
s("\t\t\t\tLastUpgradeCheck = 1500;")
s("\t\t\t\tTargetAttributes = {")
s(f"\t\t\t\t\t{TARGET} = {{")
s("\t\t\t\t\t\tCreatedOnToolsVersion = 15.0;")
s("\t\t\t\t\t};")
s("\t\t\t\t};")
s("\t\t\t};")
s(f'\t\t\tbuildConfigurationList = {PCL} /* Build configuration list for PBXProject "EMSRouting" */;')
s('\t\t\tcompatibilityVersion = "Xcode 14.0";')
s("\t\t\tdevelopmentRegion = en;")
s("\t\t\thasScannedForEncodings = 0;")
s("\t\t\tknownRegions = (")
s("\t\t\t\ten,")
s("\t\t\t\tBase,")
s("\t\t\t);")
s(f"\t\t\tmainGroup = {MG};")
s(f"\t\t\tproductsGroup = {PG} /* Products */;")
s('\t\t\tprojectDirPath = "";')
s('\t\t\tprojectRoot = "";')
s("\t\t\ttargets = (")
s(f"\t\t\t\t{TARGET} /* EMSRouting */,")
s("\t\t\t);")
s("\t\t};")
s("/* End PBXProject section */")
s()
s("/* Begin PBXResourcesBuildPhase section */")
s(f"\t\t{RES_PH} /* Resources */ = {{")
s("\t\t\tisa = PBXResourcesBuildPhase;")
s("\t\t\tbuildActionMask = 2147483647;")
s("\t\t\tfiles = (")
s(f"\t\t\t\t{ABF} /* Assets.xcassets in Resources */,")
s(f"\t\t\t\t{JBF} /* hospitals.json in Resources */,")
s("\t\t\t);")
s("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
s("\t\t};")
s("/* End PBXResourcesBuildPhase section */")
s()
s("/* Begin PBXSourcesBuildPhase section */")
s(f"\t\t{SRC_PH} /* Sources */ = {{")
s("\t\t\tisa = PBXSourcesBuildPhase;")
s("\t\t\tbuildActionMask = 2147483647;")
s("\t\t\tfiles = (")
for name, _, bf in FILES:
    s(f"\t\t\t\t{bf} /* {name} in Sources */,")
s("\t\t\t);")
s("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
s("\t\t};")
s("/* End PBXSourcesBuildPhase section */")
s()
s("/* Begin XCBuildConfiguration section */")

# Project Debug
s(f"\t\t{PDBG} /* Debug */ = {{")
s("\t\t\tisa = XCBuildConfiguration;")
s("\t\t\tbuildSettings = {")
s("\t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;")
s('\t\t\t\tCLANG_CXX_LANGUAGE_STANDARD = "gnu++20";')
s("\t\t\t\tCLANG_ENABLE_MODULES = YES;")
s("\t\t\t\tCLANG_ENABLE_OBJC_ARC = YES;")
s("\t\t\t\tCLANG_ENABLE_OBJC_WEAK = YES;")
s("\t\t\t\tCOPY_PHASE_STRIP = NO;")
s("\t\t\t\tDEBUG_INFORMATION_FORMAT = dwarf;")
s("\t\t\t\tENABLE_TESTABILITY = YES;")
s("\t\t\t\tGCC_C_LANGUAGE_STANDARD = gnu11;")
s("\t\t\t\tGCC_DYNAMIC_NO_PIC = NO;")
s("\t\t\t\tGCC_NO_COMMON_BLOCKS = YES;")
s("\t\t\t\tGCC_OPTIMIZATION_LEVEL = 0;")
s("\t\t\t\tGCC_PREPROCESSOR_DEFINITIONS = (")
s('\t\t\t\t\t"DEBUG=1",')
s('\t\t\t\t\t"$(inherited)",')
s("\t\t\t\t);")
s("\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = 16.0;")
s("\t\t\t\tMTL_ENABLE_DEBUG_INFO = INCLUDE_SOURCE;")
s("\t\t\t\tMTL_FAST_MATH = YES;")
s("\t\t\t\tONLY_ACTIVE_ARCH = YES;")
s("\t\t\t\tSDKROOT = iphoneos;")
s("\t\t\t\tSWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG;")
s('\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = "-Onone";')
s("\t\t\t};")
s("\t\t\tname = Debug;")
s("\t\t};")

# Project Release
s(f"\t\t{PREL} /* Release */ = {{")
s("\t\t\tisa = XCBuildConfiguration;")
s("\t\t\tbuildSettings = {")
s("\t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;")
s('\t\t\t\tCLANG_CXX_LANGUAGE_STANDARD = "gnu++20";')
s("\t\t\t\tCLANG_ENABLE_MODULES = YES;")
s("\t\t\t\tCLANG_ENABLE_OBJC_ARC = YES;")
s("\t\t\t\tCLANG_ENABLE_OBJC_WEAK = YES;")
s("\t\t\t\tCOPY_PHASE_STRIP = NO;")
s('\t\t\t\tDEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";')
s("\t\t\t\tENABLE_NS_ASSERTIONS = NO;")
s("\t\t\t\tGCC_C_LANGUAGE_STANDARD = gnu11;")
s("\t\t\t\tGCC_NO_COMMON_BLOCKS = YES;")
s("\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = 16.0;")
s("\t\t\t\tMTL_FAST_MATH = YES;")
s("\t\t\t\tSDKROOT = iphoneos;")
s("\t\t\t\tSWIFT_COMPILATION_MODE = wholemodule;")
s('\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = "-O";')
s("\t\t\t\tVALIDATE_PRODUCT = YES;")
s("\t\t\t};")
s("\t\t\tname = Release;")
s("\t\t};")

# Target Debug
s(f"\t\t{TDBG} /* Debug */ = {{")
s("\t\t\tisa = XCBuildConfiguration;")
s("\t\t\tbuildSettings = {")
s("\t\t\t\tASETCATALOG_COMPILER_APPICON_NAME = AppIcon;")
s("\t\t\t\tASETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor;")
s("\t\t\t\tCODE_SIGN_STYLE = Automatic;")
s("\t\t\t\tCURRENT_PROJECT_VERSION = 1;")
s("\t\t\t\tENABLE_PREVIEWS = YES;")
s("\t\t\t\tGENERATE_INFOPLIST_FILE = NO;")
s("\t\t\t\tINFOPLIST_FILE = EMSRouting/Info.plist;")
s("\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = 16.0;")
s("\t\t\t\tMARKETING_VERSION = 1.0;")
s('\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = "com.emsrouting.app";')
s("\t\t\t\tPRODUCT_NAME = \"$(TARGET_NAME)\";")
s("\t\t\t\tSDKROOT = iphoneos;")
s('\t\t\t\tSUPPORTED_PLATFORMS = "iphoneos iphonesimulator";')
s("\t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;")
s("\t\t\t\tSWIFT_VERSION = 5.0;")
s('\t\t\t\tTARGETED_DEVICE_FAMILY = "1,2";')
s("\t\t\t};")
s("\t\t\tname = Debug;")
s("\t\t};")

# Target Release
s(f"\t\t{TREL} /* Release */ = {{")
s("\t\t\tisa = XCBuildConfiguration;")
s("\t\t\tbuildSettings = {")
s("\t\t\t\tASETCATALOG_COMPILER_APPICON_NAME = AppIcon;")
s("\t\t\t\tASETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor;")
s("\t\t\t\tCODE_SIGN_STYLE = Automatic;")
s("\t\t\t\tCURRENT_PROJECT_VERSION = 1;")
s("\t\t\t\tENABLE_PREVIEWS = YES;")
s("\t\t\t\tGENERATE_INFOPLIST_FILE = NO;")
s("\t\t\t\tINFOPLIST_FILE = EMSRouting/Info.plist;")
s("\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = 16.0;")
s("\t\t\t\tMARKETING_VERSION = 1.0;")
s('\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = "com.emsrouting.app";')
s("\t\t\t\tPRODUCT_NAME = \"$(TARGET_NAME)\";")
s("\t\t\t\tSDKROOT = iphoneos;")
s('\t\t\t\tSUPPORTED_PLATFORMS = "iphoneos iphonesimulator";')
s("\t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;")
s("\t\t\t\tSWIFT_VERSION = 5.0;")
s('\t\t\t\tTARGETED_DEVICE_FAMILY = "1,2";')
s("\t\t\t};")
s("\t\t\tname = Release;")
s("\t\t};")
s("/* End XCBuildConfiguration section */")
s()
s("/* Begin XCConfigurationList section */")
s(f"\t\t{PCL} /* Build configuration list for PBXProject \"EMSRouting\" */ = {{")
s("\t\t\tisa = XCConfigurationList;")
s("\t\t\tbuildConfigurations = (")
s(f"\t\t\t\t{PDBG} /* Debug */,")
s(f"\t\t\t\t{PREL} /* Release */,")
s("\t\t\t);")
s("\t\t\tdefaultConfigurationIsVisible = 0;")
s("\t\t\tdefaultConfigurationName = Release;")
s("\t\t};")
s(f"\t\t{TCL} /* Build configuration list for PBXNativeTarget \"EMSRouting\" */ = {{")
s("\t\t\tisa = XCConfigurationList;")
s("\t\t\tbuildConfigurations = (")
s(f"\t\t\t\t{TDBG} /* Debug */,")
s(f"\t\t\t\t{TREL} /* Release */,")
s("\t\t\t);")
s("\t\t\tdefaultConfigurationIsVisible = 0;")
s("\t\t\tdefaultConfigurationName = Release;")
s("\t\t};")
s("/* End XCConfigurationList section */")
s("\t};")
s(f"\trootObject = {P} /* Project object */;")
s("}")

with open(OUT, "w") as f:
    f.write("\n".join(L) + "\n")

print(f"Generated: {OUT}")
